pipeline {
    agent any

    triggers{
        githubPush()
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                ./gradlew build
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
        stage('Playing') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
