pipeline {
    agent any

    triggers{
        githubPush()
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building in ...'
                echo pwd()
                sh './gradlew clean build'
                sh './gradlew showVersion'
            }
        }
    }
}
